### ISSUE TITLE
Change distributionManagmeent to release to Central Repository

### ISSUE THREAD

**Issue by jonespm** [azeckoski/reflectutils#2]
Should change poms to release artifacts to Maven Central instead of source.sakaiproject.org. Relates to issue filed on https://code.google.com/p/reflectutils/issues/detail?id=15&can=1.

**Comment by buckett** [comment]
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by buckett** [comment]
It would be good to get a snapshot released to the OSS Snapshot repository so we could test this without having to build locally, is there anything I can do to help with this?

**Comment by azeckoski** [comment]
I'm open to suggestions. I think I applied to try to get a space in there
but not sure what the next steps would be (just haven't had much time to
dig into it).

On Wed, Apr 1, 2015 at 6:27 AM, Matthew Buckett <notifications@github.com>
wrote:

> It would be good to get a snapshot released to the OSS Snapshot repository
> so we could test this without having to build locally, is there anything I
> can do to help with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azeckoski/reflectutils/issues/2#issuecomment-88431318>
> .
>



-- 
Aaron Zeckoski - Software Architect - http://tinyurl.com/azprofile

**Comment by jonespm** [comment]
I agree, it looks like from https://issues.sonatype.org/browse/OSSRH-9134 that it's ready to go. I can submit a PR to have the pom updated then if you were going to deploy snapshots with maven that sounds like all that would be necessary.

**Comment by azeckoski** [comment]
Sounds like a plan
:-)

On Thu, Apr 2, 2015 at 1:29 PM, Code Hugger (Matthew Jones) <
notifications@github.com> wrote:

> I agree, it looks like from https://issues.sonatype.org/browse/OSSRH-9134
> that it's ready to go. I can submit a PR to have the pom updated then if
> you were going to deploy snapshots with maven that sounds like all that
> would be necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azeckoski/reflectutils/issues/2#issuecomment-88981390>
> .
>



-- 
Aaron Zeckoski - Software Architect - http://tinyurl.com/azprofile

**Comment by buckett** [comment]
Presumably you've got the credentials for Sonatype so are you able to deploy a snapshot there now @azeckoski ?

I think you'll need to edit your `~/.m2/settings.xml` to include your Sonatype credentials: http://central.sonatype.org/pages/apache-maven.html

**Comment by azeckoski** [comment]
Should be done now.
https://oss.sonatype.org/content/repositories/releases/org/azeckoski/reflectutils/0.9.20/

Description:
org.azeckoski:reflectutils:0.9.20

Deployer properties:
"userAgent" = "Nexus-Client/2.7.2-01"
"userId" = "azeckoski"
"ip" = "75.190.132.180"

Details:

The following artifacts have been promoted to the "Releases" [id=releases] repository

/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20-javadoc.jar.asc
(SHA1: ee21d493a43a0c28b0f3fd26bab047c2aa973a2c)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20.jar.asc
(SHA1: b2868351e021b1334372d4cf615bc57147ea096a)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20-javadoc.jar
(SHA1: b8c1ec21a6bdfb2086370c08e2ca3d76ac3412b4)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20.jar
(SHA1: c4e36085243e8e3e004651d9583caf22d4738420)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20.pom
(SHA1: 9f5fa40da0dd258cfdaa682e82614f1bbfc4001c)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20-sources.jar.asc
(SHA1: 62f25cbb3aadb6f46a1039770bb27bd502e0d9be)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20-sources.jar
(SHA1: 3ca0838cd90fc1987d48ab11950a856ce245dcc4)
/org/azeckoski/reflectutils/0.9.20/reflectutils-0.9.20.pom.asc
(SHA1: 0d9396069e9ba7faed6a0d1bd462d9bd9a370fa2)

Action performed by Aaron Zeckoski
